<?php
/**
 * SiteRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Adserver
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Copyright (c) 2020 Adserver.Online
 * Contact: support@adsrv.org
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Adserver\Model;

use \Adserver\ObjectSerializer;
use \ArrayAccess;

/**
 * SiteRequest Class Doc Comment
 *
 * @category Class
 * @package  Adserver
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SiteRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SiteRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'url' => 'string',
        'idcategory' => 'int',
        'idpublisher' => 'int',
        'is_active' => 'int',
        'idstatus' => 'int',
        'idblockreason' => 'string',
        'block_reason' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'name' => null,
        'url' => null,
        'idcategory' => null,
        'idpublisher' => null,
        'is_active' => null,
        'idstatus' => null,
        'idblockreason' => null,
        'block_reason' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'url' => 'url',
        'idcategory' => 'idcategory',
        'idpublisher' => 'idpublisher',
        'is_active' => 'is_active',
        'idstatus' => 'idstatus',
        'idblockreason' => 'idblockreason',
        'block_reason' => 'block_reason'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'url' => 'setUrl',
        'idcategory' => 'setIdcategory',
        'idpublisher' => 'setIdpublisher',
        'is_active' => 'setIsActive',
        'idstatus' => 'setIdstatus',
        'idblockreason' => 'setIdblockreason',
        'block_reason' => 'setBlockReason'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'url' => 'getUrl',
        'idcategory' => 'getIdcategory',
        'idpublisher' => 'getIdpublisher',
        'is_active' => 'getIsActive',
        'idstatus' => 'getIdstatus',
        'idblockreason' => 'getIdblockreason',
        'block_reason' => 'getBlockReason'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const IS_ACTIVE_0 = 0;
    const IS_ACTIVE_1 = 1;
    const IDSTATUS_3500 = 3500;
    const IDSTATUS_3510 = 3510;
    const IDSTATUS_3520 = 3520;
    const IDBLOCKREASON__1 = '1';
    const IDBLOCKREASON__2 = '2';
    const IDBLOCKREASON__100 = '100';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIsActiveAllowableValues()
    {
        return [
            self::IS_ACTIVE_0,
            self::IS_ACTIVE_1,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIdstatusAllowableValues()
    {
        return [
            self::IDSTATUS_3500,
            self::IDSTATUS_3510,
            self::IDSTATUS_3520,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getIdblockreasonAllowableValues()
    {
        return [
            self::IDBLOCKREASON__1,
            self::IDBLOCKREASON__2,
            self::IDBLOCKREASON__100,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['idcategory'] = isset($data['idcategory']) ? $data['idcategory'] : null;
        $this->container['idpublisher'] = isset($data['idpublisher']) ? $data['idpublisher'] : null;
        $this->container['is_active'] = isset($data['is_active']) ? $data['is_active'] : null;
        $this->container['idstatus'] = isset($data['idstatus']) ? $data['idstatus'] : null;
        $this->container['idblockreason'] = isset($data['idblockreason']) ? $data['idblockreason'] : null;
        $this->container['block_reason'] = isset($data['block_reason']) ? $data['block_reason'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['idcategory'] === null) {
            $invalidProperties[] = "'idcategory' can't be null";
        }
        $allowedValues = $this->getIsActiveAllowableValues();
        if (!is_null($this->container['is_active']) && !in_array($this->container['is_active'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'is_active', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['idstatus'] === null) {
            $invalidProperties[] = "'idstatus' can't be null";
        }
        $allowedValues = $this->getIdstatusAllowableValues();
        if (!is_null($this->container['idstatus']) && !in_array($this->container['idstatus'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'idstatus', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getIdblockreasonAllowableValues();
        if (!is_null($this->container['idblockreason']) && !in_array($this->container['idblockreason'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'idblockreason', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets idcategory
     *
     * @return int
     */
    public function getIdcategory()
    {
        return $this->container['idcategory'];
    }

    /**
     * Sets idcategory
     *
     * @param int $idcategory idcategory
     *
     * @return $this
     */
    public function setIdcategory($idcategory)
    {
        $this->container['idcategory'] = $idcategory;

        return $this;
    }

    /**
     * Gets idpublisher
     *
     * @return int|null
     */
    public function getIdpublisher()
    {
        return $this->container['idpublisher'];
    }

    /**
     * Sets idpublisher
     *
     * @param int|null $idpublisher idpublisher
     *
     * @return $this
     */
    public function setIdpublisher($idpublisher)
    {
        $this->container['idpublisher'] = $idpublisher;

        return $this;
    }

    /**
     * Gets is_active
     *
     * @return int|null
     */
    public function getIsActive()
    {
        return $this->container['is_active'];
    }

    /**
     * Sets is_active
     *
     * @param int|null $is_active is_active
     *
     * @return $this
     */
    public function setIsActive($is_active)
    {
        $allowedValues = $this->getIsActiveAllowableValues();
        if (!is_null($is_active) && !in_array($is_active, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'is_active', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['is_active'] = $is_active;

        return $this;
    }

    /**
     * Gets idstatus
     *
     * @return int
     */
    public function getIdstatus()
    {
        return $this->container['idstatus'];
    }

    /**
     * Sets idstatus
     *
     * @param int $idstatus Moderation statuses:  * 3520 - pending  * 3500 - approved  * 3510 - rejected
     *
     * @return $this
     */
    public function setIdstatus($idstatus)
    {
        $allowedValues = $this->getIdstatusAllowableValues();
        if (!in_array($idstatus, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'idstatus', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['idstatus'] = $idstatus;

        return $this;
    }

    /**
     * Gets idblockreason
     *
     * @return string|null
     */
    public function getIdblockreason()
    {
        return $this->container['idblockreason'];
    }

    /**
     * Sets idblockreason
     *
     * @param string|null $idblockreason Block reason:  * 1 - low traffic quality  * 2 - illegal content  * 100 - custom
     *
     * @return $this
     */
    public function setIdblockreason($idblockreason)
    {
        $allowedValues = $this->getIdblockreasonAllowableValues();
        if (!is_null($idblockreason) && !in_array($idblockreason, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'idblockreason', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['idblockreason'] = $idblockreason;

        return $this;
    }

    /**
     * Gets block_reason
     *
     * @return string|null
     */
    public function getBlockReason()
    {
        return $this->container['block_reason'];
    }

    /**
     * Sets block_reason
     *
     * @param string|null $block_reason block_reason
     *
     * @return $this
     */
    public function setBlockReason($block_reason)
    {
        $this->container['block_reason'] = $block_reason;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


